export const LOAD_USERS = 'LOAD_USERS';
export const GET_SINGLEUSER = 'GET_SINGLEUSER';
export const GET_SINGLEUSER_REPOS = 'GET_SINGLEUSER_REPOS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const CLEAR_USERS = 'CLEAR_USERS';
export const SET_LOADING = 'SET_LOADING';
export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

